
////////////////////////////////////////////////////////////////////////////////////////
////// Autogenerated by JaySvcUtil.exe http://JayData.org for more info        /////////
//////                             oData v1                                    /////////
////////////////////////////////////////////////////////////////////////////////////////

(function(global, $data, undefined) {

  
  

  function registerEdmTypes() {
  
    function Edm_Boolean() { };
    $data.Container.registerType('Edm.Boolean', Edm_Boolean);
    $data.Container.mapType(Edm_Boolean, $data.Boolean);
    
    function Edm_Binary() { };
    $data.Container.registerType('Edm.Binary', Edm_Binary);
    $data.Container.mapType(Edm_Binary, $data.Blob);
    
    function Edm_DateTime() { };
    $data.Container.registerType('Edm.DateTime', Edm_DateTime);
    $data.Container.mapType(Edm_DateTime, $data.Date);
    
    function Edm_DateTimeOffset() { };
    $data.Container.registerType('Edm.DateTimeOffset', Edm_DateTimeOffset);
    $data.Container.mapType(Edm_DateTimeOffset, $data.Integer);
    
    function Edm_Time() { };
    $data.Container.registerType('Edm.Time', Edm_Time);
    $data.Container.mapType(Edm_Time, $data.Integer);
    
    function Edm_Decimal() { };
    $data.Container.registerType('Edm.Decimal', Edm_Decimal);
    $data.Container.mapType(Edm_Decimal, $data.Number);
    
    function Edm_Single() { };
    $data.Container.registerType('Edm.Single', Edm_Single);
    $data.Container.mapType(Edm_Single, $data.Number);
    
    function Edm_Double() { };
    $data.Container.registerType('Edm.Double', Edm_Double);
    $data.Container.mapType(Edm_Double, $data.Number);
    
    function Edm_Guid() { };
    $data.Container.registerType('Edm.Guid', Edm_Guid);
    $data.Container.mapType(Edm_Guid, $data.String);
    
    function Edm_Int16() { };
    $data.Container.registerType('Edm.Int16', Edm_Int16);
    $data.Container.mapType(Edm_Int16, $data.Integer);
    
    function Edm_Int32() { };
    $data.Container.registerType('Edm.Int32', Edm_Int32);
    $data.Container.mapType(Edm_Int32, $data.Integer);
    
    function Edm_Int64() { };
    $data.Container.registerType('Edm.Int64', Edm_Int64);
    $data.Container.mapType(Edm_Int64, $data.Integer);
    
    function Edm_Byte() { };
    $data.Container.registerType('Edm.Byte', Edm_Byte);
    $data.Container.mapType(Edm_Byte, $data.Integer);
    
    function Edm_String() { };
    $data.Container.registerType('Edm.String', Edm_String);
    $data.Container.mapType(Edm_String, $data.String);
    
  };
  registerEdmTypes();
  $data.Entity.extend('Microsoft.SharePoint.DataService.AnnouncementsItem', {
    'Id': { key:true,type:'Edm.Int32',nullable:false,required:true },
    'ContentTypeID': { type:'Edm.String',nullable:true },
    'ContentType': { type:'Edm.String',nullable:true },
    'Title': { type:'Edm.String',nullable:true },
    'Modified': { type:'Edm.DateTime',nullable:true },
    'Created': { type:'Edm.DateTime',nullable:true },
    'CreatedBy': { type:'Microsoft.SharePoint.DataService.UserInformationListItem',inverseProperty:'$$unbound' },
    'CreatedById': { type:'Edm.Int32',nullable:true },
    'ModifiedBy': { type:'Microsoft.SharePoint.DataService.UserInformationListItem',inverseProperty:'$$unbound' },
    'ModifiedById': { type:'Edm.Int32',nullable:true },
    'Owshiddenversion': { type:'Edm.Int32',nullable:true,concurrencyMode:$data.ConcurrencyMode.Fixed },
    'Version': { type:'Edm.String',nullable:true },
    'Attachments': { type:'Array',elementType:'Microsoft.SharePoint.DataService.AttachmentsItem',inverseProperty:'$$unbound' },
    'Path': { type:'Edm.String',nullable:true },
    'Body': { type:'Edm.String',nullable:true },
    'Expires': { type:'Edm.DateTime',nullable:true }
  });
  $data.Entity.extend('Microsoft.SharePoint.DataService.AttachmentsItem', {
    'EntitySet': { key:true,type:'Edm.String',nullable:false,required:true },
    'ItemId': { key:true,type:'Edm.Int32',nullable:false,required:true },
    'Name': { key:true,type:'Edm.String',nullable:false,required:true }
  });
  $data.Entity.extend('Microsoft.SharePoint.DataService.CalendarItem', {
    'Id': { key:true,type:'Edm.Int32',nullable:false,required:true },
    'ContentTypeID': { type:'Edm.String',nullable:true },
    'ContentType': { type:'Edm.String',nullable:true },
    'Title': { type:'Edm.String',nullable:true },
    'Modified': { type:'Edm.DateTime',nullable:true },
    'Created': { type:'Edm.DateTime',nullable:true },
    'CreatedBy': { type:'Microsoft.SharePoint.DataService.UserInformationListItem',inverseProperty:'$$unbound' },
    'CreatedById': { type:'Edm.Int32',nullable:true },
    'ModifiedBy': { type:'Microsoft.SharePoint.DataService.UserInformationListItem',inverseProperty:'$$unbound' },
    'ModifiedById': { type:'Edm.Int32',nullable:true },
    'Owshiddenversion': { type:'Edm.Int32',nullable:true,concurrencyMode:$data.ConcurrencyMode.Fixed },
    'Version': { type:'Edm.String',nullable:true },
    'Attachments': { type:'Array',elementType:'Microsoft.SharePoint.DataService.AttachmentsItem',inverseProperty:'$$unbound' },
    'Path': { type:'Edm.String',nullable:true },
    'Location': { type:'Edm.String',nullable:true },
    'StartTime': { type:'Edm.DateTime',nullable:true },
    'EndTime': { type:'Edm.DateTime',nullable:true },
    'Description': { type:'Edm.String',nullable:true },
    'AllDayEvent': { type:'Edm.Boolean',nullable:true },
    'Recurrence': { type:'Edm.Boolean',nullable:true },
    'Workspace': { type:'Edm.Boolean',nullable:true },
    'Attendees': { type:'Array',elementType:'Microsoft.SharePoint.DataService.UserInformationListItem',inverseProperty:'$$unbound' },
    'Category': { type:'Microsoft.SharePoint.DataService.CalendarCategoryValue',inverseProperty:'$$unbound' },
    'CategoryValue': { type:'Edm.String',nullable:true }
  });
  $data.Entity.extend('Microsoft.SharePoint.DataService.CalendarCategoryValue', {
    'Value': { key:true,type:'Edm.String',nullable:false,required:true }
  });
  $data.Entity.extend('Microsoft.SharePoint.DataService.ContactsItem', {
    'Id': { key:true,type:'Edm.Int32',nullable:false,required:true },
    'ContentTypeID': { type:'Edm.String',nullable:true },
    'ContentType': { type:'Edm.String',nullable:true },
    'LastName': { type:'Edm.String',nullable:true },
    'Modified': { type:'Edm.DateTime',nullable:true },
    'Created': { type:'Edm.DateTime',nullable:true },
    'CreatedBy': { type:'Microsoft.SharePoint.DataService.UserInformationListItem',inverseProperty:'$$unbound' },
    'CreatedById': { type:'Edm.Int32',nullable:true },
    'ModifiedBy': { type:'Microsoft.SharePoint.DataService.UserInformationListItem',inverseProperty:'$$unbound' },
    'ModifiedById': { type:'Edm.Int32',nullable:true },
    'Owshiddenversion': { type:'Edm.Int32',nullable:true,concurrencyMode:$data.ConcurrencyMode.Fixed },
    'Version': { type:'Edm.String',nullable:true },
    'Attachments': { type:'Array',elementType:'Microsoft.SharePoint.DataService.AttachmentsItem',inverseProperty:'$$unbound' },
    'Path': { type:'Edm.String',nullable:true },
    'FirstName': { type:'Edm.String',nullable:true },
    'FullName': { type:'Edm.String',nullable:true },
    'EMailAddress': { type:'Edm.String',nullable:true },
    'Company': { type:'Edm.String',nullable:true },
    'JobTitle': { type:'Edm.String',nullable:true },
    'BusinessPhone': { type:'Edm.String',nullable:true },
    'HomePhone': { type:'Edm.String',nullable:true },
    'MobileNumber': { type:'Edm.String',nullable:true },
    'FaxNumber': { type:'Edm.String',nullable:true },
    'Address': { type:'Edm.String',nullable:true },
    'City': { type:'Edm.String',nullable:true },
    'StateProvince': { type:'Edm.String',nullable:true },
    'ZIPPostalCode': { type:'Edm.String',nullable:true },
    'CountryRegion': { type:'Edm.String',nullable:true },
    'WebPage': { type:'Edm.String',nullable:true },
    'Notes': { type:'Edm.String',nullable:true },
    'Task': { type:'Microsoft.SharePoint.DataService.TasksItem',inverseProperty:'$$unbound' },
    'TaskId': { type:'Edm.Int32',nullable:true }
  });
  $data.Entity.extend('Microsoft.SharePoint.DataService.Custom1Item', {
    'Id': { key:true,type:'Edm.Int32',nullable:false,required:true },
    'ContentTypeID': { type:'Edm.String',nullable:true },
    'ContentType': { type:'Edm.String',nullable:true },
    'Title': { type:'Edm.String',nullable:true },
    'Modified': { type:'Edm.DateTime',nullable:true },
    'Created': { type:'Edm.DateTime',nullable:true },
    'CreatedBy': { type:'Microsoft.SharePoint.DataService.UserInformationListItem',inverseProperty:'$$unbound' },
    'CreatedById': { type:'Edm.Int32',nullable:true },
    'ModifiedBy': { type:'Microsoft.SharePoint.DataService.UserInformationListItem',inverseProperty:'$$unbound' },
    'ModifiedById': { type:'Edm.Int32',nullable:true },
    'Owshiddenversion': { type:'Edm.Int32',nullable:true,concurrencyMode:$data.ConcurrencyMode.Fixed },
    'Version': { type:'Edm.String',nullable:true },
    'Attachments': { type:'Array',elementType:'Microsoft.SharePoint.DataService.AttachmentsItem',inverseProperty:'$$unbound' },
    'Path': { type:'Edm.String',nullable:true }
  });
  $data.Entity.extend('Microsoft.SharePoint.DataService.DocumentLibrary1Item', {
    'Id': { key:true,type:'Edm.Int32',nullable:false,required:true },
    'ContentTypeID': { type:'Edm.String',nullable:true },
    'ContentType': { type:'Edm.String',nullable:true },
    'Created': { type:'Edm.DateTime',nullable:true },
    'CreatedBy': { type:'Microsoft.SharePoint.DataService.UserInformationListItem',inverseProperty:'$$unbound' },
    'CreatedById': { type:'Edm.Int32',nullable:true },
    'Modified': { type:'Edm.DateTime',nullable:true },
    'ModifiedBy': { type:'Microsoft.SharePoint.DataService.UserInformationListItem',inverseProperty:'$$unbound' },
    'ModifiedById': { type:'Edm.Int32',nullable:true },
    'CopySource': { type:'Edm.String',nullable:true },
    'ApprovalStatus': { type:'Edm.String',nullable:true },
    'Path': { type:'Edm.String',nullable:true },
    'CheckedOutTo': { type:'Microsoft.SharePoint.DataService.UserInformationListItem',inverseProperty:'$$unbound' },
    'CheckedOutToId': { type:'Edm.Int32',nullable:true },
    'Name': { type:'Edm.String',nullable:true },
    'VirusStatus': { type:'Edm.String',nullable:true },
    'IsCurrentVersion': { type:'Edm.Boolean',nullable:true },
    'Owshiddenversion': { type:'Edm.Int32',nullable:true,concurrencyMode:$data.ConcurrencyMode.Fixed },
    'Version': { type:'Edm.String',nullable:true },
    'Title': { type:'Edm.String',nullable:true }
  });
  $data.Entity.extend('Microsoft.SharePoint.DataService.DocumentLibrary2Item', {
    'Id': { key:true,type:'Edm.Int32',nullable:false,required:true },
    'ContentTypeID': { type:'Edm.String',nullable:true },
    'ContentType': { type:'Edm.String',nullable:true },
    'Created': { type:'Edm.DateTime',nullable:true },
    'CreatedBy': { type:'Microsoft.SharePoint.DataService.UserInformationListItem',inverseProperty:'$$unbound' },
    'CreatedById': { type:'Edm.Int32',nullable:true },
    'Modified': { type:'Edm.DateTime',nullable:true },
    'ModifiedBy': { type:'Microsoft.SharePoint.DataService.UserInformationListItem',inverseProperty:'$$unbound' },
    'ModifiedById': { type:'Edm.Int32',nullable:true },
    'CopySource': { type:'Edm.String',nullable:true },
    'ApprovalStatus': { type:'Edm.String',nullable:true },
    'Path': { type:'Edm.String',nullable:true },
    'CheckedOutTo': { type:'Microsoft.SharePoint.DataService.UserInformationListItem',inverseProperty:'$$unbound' },
    'CheckedOutToId': { type:'Edm.Int32',nullable:true },
    'Name': { type:'Edm.String',nullable:true },
    'VirusStatus': { type:'Edm.String',nullable:true },
    'IsCurrentVersion': { type:'Edm.Boolean',nullable:true },
    'Owshiddenversion': { type:'Edm.Int32',nullable:true,concurrencyMode:$data.ConcurrencyMode.Fixed },
    'Version': { type:'Edm.String',nullable:true },
    'Title': { type:'Edm.String',nullable:true }
  });
  $data.Entity.extend('Microsoft.SharePoint.DataService.FpdatasourcesItem', {
    'Id': { key:true,type:'Edm.Int32',nullable:false,required:true },
    'ContentTypeID': { type:'Edm.String',nullable:true },
    'ContentType': { type:'Edm.String',nullable:true },
    'Created': { type:'Edm.DateTime',nullable:true },
    'CreatedBy': { type:'Microsoft.SharePoint.DataService.UserInformationListItem',inverseProperty:'$$unbound' },
    'CreatedById': { type:'Edm.Int32',nullable:true },
    'Modified': { type:'Edm.DateTime',nullable:true },
    'ModifiedBy': { type:'Microsoft.SharePoint.DataService.UserInformationListItem',inverseProperty:'$$unbound' },
    'ModifiedById': { type:'Edm.Int32',nullable:true },
    'CopySource': { type:'Edm.String',nullable:true },
    'ApprovalStatus': { type:'Edm.String',nullable:true },
    'Path': { type:'Edm.String',nullable:true },
    'CheckedOutTo': { type:'Microsoft.SharePoint.DataService.UserInformationListItem',inverseProperty:'$$unbound' },
    'CheckedOutToId': { type:'Edm.Int32',nullable:true },
    'Name': { type:'Edm.String',nullable:true },
    'VirusStatus': { type:'Edm.String',nullable:true },
    'IsCurrentVersion': { type:'Edm.Boolean',nullable:true },
    'Owshiddenversion': { type:'Edm.Int32',nullable:true,concurrencyMode:$data.ConcurrencyMode.Fixed },
    'Version': { type:'Edm.String',nullable:true }
  });
  $data.Entity.extend('Microsoft.SharePoint.DataService.FunnyÜÖÄüöäNameItem', {
    'Id': { key:true,type:'Edm.Int32',nullable:false,required:true },
    'ContentTypeID': { type:'Edm.String',nullable:true },
    'ContentType': { type:'Edm.String',nullable:true },
    'Title': { type:'Edm.String',nullable:true },
    'Modified': { type:'Edm.DateTime',nullable:true },
    'Created': { type:'Edm.DateTime',nullable:true },
    'CreatedBy': { type:'Microsoft.SharePoint.DataService.UserInformationListItem',inverseProperty:'$$unbound' },
    'CreatedById': { type:'Edm.Int32',nullable:true },
    'ModifiedBy': { type:'Microsoft.SharePoint.DataService.UserInformationListItem',inverseProperty:'$$unbound' },
    'ModifiedById': { type:'Edm.Int32',nullable:true },
    'Owshiddenversion': { type:'Edm.Int32',nullable:true,concurrencyMode:$data.ConcurrencyMode.Fixed },
    'Version': { type:'Edm.String',nullable:true },
    'Attachments': { type:'Array',elementType:'Microsoft.SharePoint.DataService.AttachmentsItem',inverseProperty:'$$unbound' },
    'Path': { type:'Edm.String',nullable:true }
  });
  $data.Entity.extend('Microsoft.SharePoint.DataService.IssuesItem', {
    'Id': { key:true,type:'Edm.Int32',nullable:false,required:true },
    'ContentTypeID': { type:'Edm.String',nullable:true },
    'ContentType': { type:'Edm.String',nullable:true },
    'Title': { type:'Edm.String',nullable:true },
    'Modified': { type:'Edm.DateTime',nullable:true },
    'Created': { type:'Edm.DateTime',nullable:true },
    'CreatedBy': { type:'Microsoft.SharePoint.DataService.UserInformationListItem',inverseProperty:'$$unbound' },
    'CreatedById': { type:'Edm.Int32',nullable:true },
    'ModifiedBy': { type:'Microsoft.SharePoint.DataService.UserInformationListItem',inverseProperty:'$$unbound' },
    'ModifiedById': { type:'Edm.Int32',nullable:true },
    'Owshiddenversion': { type:'Edm.Int32',nullable:true,concurrencyMode:$data.ConcurrencyMode.Fixed },
    'Version': { type:'Edm.String',nullable:true },
    'Attachments': { type:'Array',elementType:'Microsoft.SharePoint.DataService.AttachmentsItem',inverseProperty:'$$unbound' },
    'Current': { type:'Edm.Boolean',nullable:true },
    'Path': { type:'Edm.String',nullable:true },
    'AssignedTo': { type:'Microsoft.SharePoint.DataService.UserInformationListItem',inverseProperty:'$$unbound' },
    'AssignedToId': { type:'Edm.Int32',nullable:true },
    'IssueStatus': { type:'Microsoft.SharePoint.DataService.IssuesIssueStatusValue',inverseProperty:'$$unbound' },
    'IssueStatusValue': { type:'Edm.String',nullable:true },
    'Priority': { type:'Microsoft.SharePoint.DataService.IssuesPriorityValue',inverseProperty:'$$unbound' },
    'PriorityValue': { type:'Edm.String',nullable:true },
    'Description': { type:'Edm.String',nullable:true },
    'Category': { type:'Microsoft.SharePoint.DataService.IssuesCategoryValue',inverseProperty:'$$unbound' },
    'CategoryValue': { type:'Edm.String',nullable:true },
    'DueDate': { type:'Edm.DateTime',nullable:true },
    'RelatedIssues': { type:'Array',elementType:'Microsoft.SharePoint.DataService.IssuesItem',inverseProperty:'$$unbound' },
    'Comments': { type:'Edm.String',nullable:true }
  });
  $data.Entity.extend('Microsoft.SharePoint.DataService.IssuesCategoryValue', {
    'Value': { key:true,type:'Edm.String',nullable:false,required:true }
  });
  $data.Entity.extend('Microsoft.SharePoint.DataService.IssuesIssueStatusValue', {
    'Value': { key:true,type:'Edm.String',nullable:false,required:true }
  });
  $data.Entity.extend('Microsoft.SharePoint.DataService.IssuesPriorityValue', {
    'Value': { key:true,type:'Edm.String',nullable:false,required:true }
  });
  $data.Entity.extend('Microsoft.SharePoint.DataService.LinksItem', {
    'Id': { key:true,type:'Edm.Int32',nullable:false,required:true },
    'ContentTypeID': { type:'Edm.String',nullable:true },
    'ContentType': { type:'Edm.String',nullable:true },
    'Modified': { type:'Edm.DateTime',nullable:true },
    'Created': { type:'Edm.DateTime',nullable:true },
    'CreatedBy': { type:'Microsoft.SharePoint.DataService.UserInformationListItem',inverseProperty:'$$unbound' },
    'CreatedById': { type:'Edm.Int32',nullable:true },
    'ModifiedBy': { type:'Microsoft.SharePoint.DataService.UserInformationListItem',inverseProperty:'$$unbound' },
    'ModifiedById': { type:'Edm.Int32',nullable:true },
    'Owshiddenversion': { type:'Edm.Int32',nullable:true,concurrencyMode:$data.ConcurrencyMode.Fixed },
    'Version': { type:'Edm.String',nullable:true },
    'Path': { type:'Edm.String',nullable:true },
    'URL': { type:'Edm.String',nullable:true },
    'Notes': { type:'Edm.String',nullable:true }
  });
  $data.Entity.extend('Microsoft.SharePoint.DataService.ListTemplateGalleryItem', {
    'Id': { key:true,type:'Edm.Int32',nullable:false,required:true },
    'ContentTypeID': { type:'Edm.String',nullable:true },
    'ContentType': { type:'Edm.String',nullable:true },
    'Created': { type:'Edm.DateTime',nullable:true },
    'CreatedBy': { type:'Microsoft.SharePoint.DataService.UserInformationListItem',inverseProperty:'$$unbound' },
    'CreatedById': { type:'Edm.Int32',nullable:true },
    'Modified': { type:'Edm.DateTime',nullable:true },
    'ModifiedBy': { type:'Microsoft.SharePoint.DataService.UserInformationListItem',inverseProperty:'$$unbound' },
    'ModifiedById': { type:'Edm.Int32',nullable:true },
    'CopySource': { type:'Edm.String',nullable:true },
    'ApprovalStatus': { type:'Edm.String',nullable:true },
    'Path': { type:'Edm.String',nullable:true },
    'CheckedOutTo': { type:'Microsoft.SharePoint.DataService.UserInformationListItem',inverseProperty:'$$unbound' },
    'CheckedOutToId': { type:'Edm.Int32',nullable:true },
    'Name': { type:'Edm.String',nullable:true },
    'VirusStatus': { type:'Edm.String',nullable:true },
    'IsCurrentVersion': { type:'Edm.Boolean',nullable:true },
    'Owshiddenversion': { type:'Edm.Int32',nullable:true,concurrencyMode:$data.ConcurrencyMode.Fixed },
    'Version': { type:'Edm.String',nullable:true },
    'Title': { type:'Edm.String',nullable:true },
    'Description': { type:'Edm.String',nullable:true },
    'SiteDefinitionID': { type:'Edm.String',nullable:true },
    'BaseType': { type:'Edm.Int32',nullable:true },
    'ProductVersion': { type:'Edm.Double',nullable:true },
    'FeatureID': { type:'Edm.Guid',nullable:true }
  });
  $data.Entity.extend('Microsoft.SharePoint.DataService.MasterPageGalleryItem', {
    'Id': { key:true,type:'Edm.Int32',nullable:false,required:true },
    'ContentTypeID': { type:'Edm.String',nullable:true },
    'ContentType': { type:'Edm.String',nullable:true },
    'Created': { type:'Edm.DateTime',nullable:true },
    'CreatedBy': { type:'Microsoft.SharePoint.DataService.UserInformationListItem',inverseProperty:'$$unbound' },
    'CreatedById': { type:'Edm.Int32',nullable:true },
    'Modified': { type:'Edm.DateTime',nullable:true },
    'ModifiedBy': { type:'Microsoft.SharePoint.DataService.UserInformationListItem',inverseProperty:'$$unbound' },
    'ModifiedById': { type:'Edm.Int32',nullable:true },
    'CopySource': { type:'Edm.String',nullable:true },
    'ApprovalStatus': { type:'Edm.String',nullable:true },
    'Path': { type:'Edm.String',nullable:true },
    'CheckedOutTo': { type:'Microsoft.SharePoint.DataService.UserInformationListItem',inverseProperty:'$$unbound' },
    'CheckedOutToId': { type:'Edm.Int32',nullable:true },
    'Name': { type:'Edm.String',nullable:true },
    'VirusStatus': { type:'Edm.String',nullable:true },
    'IsCurrentVersion': { type:'Edm.Boolean',nullable:true },
    'Owshiddenversion': { type:'Edm.Int32',nullable:true,concurrencyMode:$data.ConcurrencyMode.Fixed },
    'Version': { type:'Edm.String',nullable:true },
    'Description': { type:'Edm.String',nullable:true },
    'CompatibleUIVersionS': { type:'Array',elementType:'Microsoft.SharePoint.DataService.MasterPageGalleryCompatibleUIVersionSValue',inverseProperty:'$$unbound' }
  });
  $data.Entity.extend('Microsoft.SharePoint.DataService.MasterPageGalleryCompatibleUIVersionSValue', {
    'Value': { key:true,type:'Edm.String',nullable:false,required:true }
  });
  $data.Entity.extend('Microsoft.SharePoint.DataService.ProjectTasksItem', {
    'Id': { key:true,type:'Edm.Int32',nullable:false,required:true },
    'ContentTypeID': { type:'Edm.String',nullable:true },
    'ContentType': { type:'Edm.String',nullable:true },
    'Title': { type:'Edm.String',nullable:true },
    'Modified': { type:'Edm.DateTime',nullable:true },
    'Created': { type:'Edm.DateTime',nullable:true },
    'CreatedBy': { type:'Microsoft.SharePoint.DataService.UserInformationListItem',inverseProperty:'$$unbound' },
    'CreatedById': { type:'Edm.Int32',nullable:true },
    'ModifiedBy': { type:'Microsoft.SharePoint.DataService.UserInformationListItem',inverseProperty:'$$unbound' },
    'ModifiedById': { type:'Edm.Int32',nullable:true },
    'Owshiddenversion': { type:'Edm.Int32',nullable:true,concurrencyMode:$data.ConcurrencyMode.Fixed },
    'Version': { type:'Edm.String',nullable:true },
    'Attachments': { type:'Array',elementType:'Microsoft.SharePoint.DataService.AttachmentsItem',inverseProperty:'$$unbound' },
    'Path': { type:'Edm.String',nullable:true },
    'Predecessors': { type:'Array',elementType:'Microsoft.SharePoint.DataService.ProjectTasksItem',inverseProperty:'$$unbound' },
    'Priority': { type:'Microsoft.SharePoint.DataService.ProjectTasksPriorityValue',inverseProperty:'$$unbound' },
    'PriorityValue': { type:'Edm.String',nullable:true },
    'TaskStatus': { type:'Microsoft.SharePoint.DataService.ProjectTasksTaskStatusValue',inverseProperty:'$$unbound' },
    'TaskStatusValue': { type:'Edm.String',nullable:true },
    'Complete': { type:'Edm.Double',nullable:true },
    'AssignedTo': { type:'Array',elementType:'Microsoft.SharePoint.DataService.UserInformationListItem',inverseProperty:'$$unbound' },
    'Description': { type:'Edm.String',nullable:true },
    'StartDate': { type:'Edm.DateTime',nullable:true },
    'DueDate': { type:'Edm.DateTime',nullable:true }
  });
  $data.Entity.extend('Microsoft.SharePoint.DataService.ProjectTasksPriorityValue', {
    'Value': { key:true,type:'Edm.String',nullable:false,required:true }
  });
  $data.Entity.extend('Microsoft.SharePoint.DataService.ProjectTasksTaskStatusValue', {
    'Value': { key:true,type:'Edm.String',nullable:false,required:true }
  });
  $data.Entity.extend('Microsoft.SharePoint.DataService.ServiceFilesItem', {
    'Id': { key:true,type:'Edm.Int32',nullable:false,required:true },
    'ContentTypeID': { type:'Edm.String',nullable:true },
    'ContentType': { type:'Edm.String',nullable:true },
    'Created': { type:'Edm.DateTime',nullable:true },
    'CreatedBy': { type:'Microsoft.SharePoint.DataService.UserInformationListItem',inverseProperty:'$$unbound' },
    'CreatedById': { type:'Edm.Int32',nullable:true },
    'Modified': { type:'Edm.DateTime',nullable:true },
    'ModifiedBy': { type:'Microsoft.SharePoint.DataService.UserInformationListItem',inverseProperty:'$$unbound' },
    'ModifiedById': { type:'Edm.Int32',nullable:true },
    'CopySource': { type:'Edm.String',nullable:true },
    'ApprovalStatus': { type:'Edm.String',nullable:true },
    'Path': { type:'Edm.String',nullable:true },
    'CheckedOutTo': { type:'Microsoft.SharePoint.DataService.UserInformationListItem',inverseProperty:'$$unbound' },
    'CheckedOutToId': { type:'Edm.Int32',nullable:true },
    'Name': { type:'Edm.String',nullable:true },
    'VirusStatus': { type:'Edm.String',nullable:true },
    'IsCurrentVersion': { type:'Edm.Boolean',nullable:true },
    'Owshiddenversion': { type:'Edm.Int32',nullable:true,concurrencyMode:$data.ConcurrencyMode.Fixed },
    'Version': { type:'Edm.String',nullable:true },
    'Title': { type:'Edm.String',nullable:true }
  });
  $data.Entity.extend('Microsoft.SharePoint.DataService.SitePagesItem', {
    'Id': { key:true,type:'Edm.Int32',nullable:false,required:true },
    'ContentTypeID': { type:'Edm.String',nullable:true },
    'ContentType': { type:'Edm.String',nullable:true },
    'Created': { type:'Edm.DateTime',nullable:true },
    'CreatedBy': { type:'Microsoft.SharePoint.DataService.UserInformationListItem',inverseProperty:'$$unbound' },
    'CreatedById': { type:'Edm.Int32',nullable:true },
    'Modified': { type:'Edm.DateTime',nullable:true },
    'ModifiedBy': { type:'Microsoft.SharePoint.DataService.UserInformationListItem',inverseProperty:'$$unbound' },
    'ModifiedById': { type:'Edm.Int32',nullable:true },
    'CopySource': { type:'Edm.String',nullable:true },
    'ApprovalStatus': { type:'Edm.String',nullable:true },
    'Path': { type:'Edm.String',nullable:true },
    'CheckedOutTo': { type:'Microsoft.SharePoint.DataService.UserInformationListItem',inverseProperty:'$$unbound' },
    'CheckedOutToId': { type:'Edm.Int32',nullable:true },
    'Name': { type:'Edm.String',nullable:true },
    'VirusStatus': { type:'Edm.String',nullable:true },
    'IsCurrentVersion': { type:'Edm.Boolean',nullable:true },
    'Owshiddenversion': { type:'Edm.Int32',nullable:true,concurrencyMode:$data.ConcurrencyMode.Fixed },
    'Version': { type:'Edm.String',nullable:true },
    'WikiContent': { type:'Edm.String',nullable:true }
  });
  $data.Entity.extend('Microsoft.SharePoint.DataService.SolutionGalleryItem', {
    'Id': { key:true,type:'Edm.Int32',nullable:false,required:true },
    'ContentTypeID': { type:'Edm.String',nullable:true },
    'ContentType': { type:'Edm.String',nullable:true },
    'Created': { type:'Edm.DateTime',nullable:true },
    'CreatedBy': { type:'Microsoft.SharePoint.DataService.UserInformationListItem',inverseProperty:'$$unbound' },
    'CreatedById': { type:'Edm.Int32',nullable:true },
    'Modified': { type:'Edm.DateTime',nullable:true },
    'ModifiedBy': { type:'Microsoft.SharePoint.DataService.UserInformationListItem',inverseProperty:'$$unbound' },
    'ModifiedById': { type:'Edm.Int32',nullable:true },
    'CopySource': { type:'Edm.String',nullable:true },
    'ApprovalStatus': { type:'Edm.String',nullable:true },
    'Path': { type:'Edm.String',nullable:true },
    'CheckedOutTo': { type:'Microsoft.SharePoint.DataService.UserInformationListItem',inverseProperty:'$$unbound' },
    'CheckedOutToId': { type:'Edm.Int32',nullable:true },
    'Name': { type:'Edm.String',nullable:true },
    'VirusStatus': { type:'Edm.String',nullable:true },
    'IsCurrentVersion': { type:'Edm.Boolean',nullable:true },
    'Owshiddenversion': { type:'Edm.Int32',nullable:true,concurrencyMode:$data.ConcurrencyMode.Fixed },
    'Version': { type:'Edm.String',nullable:true },
    'SolutionId': { type:'Edm.Guid',nullable:true },
    'Title': { type:'Edm.String',nullable:true },
    'Description': { type:'Edm.String',nullable:true },
    'Hash': { type:'Edm.String',nullable:true }
  });
  $data.Entity.extend('Microsoft.SharePoint.DataService.StyleLibraryItem', {
    'Id': { key:true,type:'Edm.Int32',nullable:false,required:true },
    'ContentTypeID': { type:'Edm.String',nullable:true },
    'ContentType': { type:'Edm.String',nullable:true },
    'Created': { type:'Edm.DateTime',nullable:true },
    'CreatedBy': { type:'Microsoft.SharePoint.DataService.UserInformationListItem',inverseProperty:'$$unbound' },
    'CreatedById': { type:'Edm.Int32',nullable:true },
    'Modified': { type:'Edm.DateTime',nullable:true },
    'ModifiedBy': { type:'Microsoft.SharePoint.DataService.UserInformationListItem',inverseProperty:'$$unbound' },
    'ModifiedById': { type:'Edm.Int32',nullable:true },
    'CopySource': { type:'Edm.String',nullable:true },
    'ApprovalStatus': { type:'Edm.String',nullable:true },
    'Path': { type:'Edm.String',nullable:true },
    'CheckedOutTo': { type:'Microsoft.SharePoint.DataService.UserInformationListItem',inverseProperty:'$$unbound' },
    'CheckedOutToId': { type:'Edm.Int32',nullable:true },
    'Name': { type:'Edm.String',nullable:true },
    'VirusStatus': { type:'Edm.String',nullable:true },
    'IsCurrentVersion': { type:'Edm.Boolean',nullable:true },
    'Owshiddenversion': { type:'Edm.Int32',nullable:true,concurrencyMode:$data.ConcurrencyMode.Fixed },
    'Version': { type:'Edm.String',nullable:true },
    'Title': { type:'Edm.String',nullable:true }
  });
  $data.Entity.extend('Microsoft.SharePoint.DataService.TasksItem', {
    'Id': { key:true,type:'Edm.Int32',nullable:false,required:true },
    'ContentTypeID': { type:'Edm.String',nullable:true },
    'ContentType': { type:'Edm.String',nullable:true },
    'Title': { type:'Edm.String',nullable:true },
    'Modified': { type:'Edm.DateTime',nullable:true },
    'Created': { type:'Edm.DateTime',nullable:true },
    'CreatedBy': { type:'Microsoft.SharePoint.DataService.UserInformationListItem',inverseProperty:'$$unbound' },
    'CreatedById': { type:'Edm.Int32',nullable:true },
    'ModifiedBy': { type:'Microsoft.SharePoint.DataService.UserInformationListItem',inverseProperty:'$$unbound' },
    'ModifiedById': { type:'Edm.Int32',nullable:true },
    'Owshiddenversion': { type:'Edm.Int32',nullable:true,concurrencyMode:$data.ConcurrencyMode.Fixed },
    'Version': { type:'Edm.String',nullable:true },
    'Attachments': { type:'Array',elementType:'Microsoft.SharePoint.DataService.AttachmentsItem',inverseProperty:'$$unbound' },
    'Path': { type:'Edm.String',nullable:true },
    'Predecessors': { type:'Array',elementType:'Microsoft.SharePoint.DataService.TasksItem',inverseProperty:'$$unbound' },
    'Priority': { type:'Microsoft.SharePoint.DataService.TasksPriorityValue',inverseProperty:'$$unbound' },
    'PriorityValue': { type:'Edm.String',nullable:true },
    'Status': { type:'Microsoft.SharePoint.DataService.TasksStatusValue',inverseProperty:'$$unbound' },
    'StatusValue': { type:'Edm.String',nullable:true },
    'Complete': { type:'Edm.Double',nullable:true },
    'AssignedTo': { type:'Microsoft.SharePoint.DataService.UserInformationListItem',inverseProperty:'$$unbound' },
    'AssignedToId': { type:'Edm.Int32',nullable:true },
    'TaskGroup': { type:'Microsoft.SharePoint.DataService.UserInformationListItem',inverseProperty:'$$unbound' },
    'TaskGroupId': { type:'Edm.Int32',nullable:true },
    'Description': { type:'Edm.String',nullable:true },
    'StartDate': { type:'Edm.DateTime',nullable:true },
    'DueDate': { type:'Edm.DateTime',nullable:true }
  });
  $data.Entity.extend('Microsoft.SharePoint.DataService.TasksPriorityValue', {
    'Value': { key:true,type:'Edm.String',nullable:false,required:true }
  });
  $data.Entity.extend('Microsoft.SharePoint.DataService.TasksStatusValue', {
    'Value': { key:true,type:'Edm.String',nullable:false,required:true }
  });
  $data.Entity.extend('Microsoft.SharePoint.DataService.ThemeGalleryItem', {
    'Id': { key:true,type:'Edm.Int32',nullable:false,required:true },
    'ContentTypeID': { type:'Edm.String',nullable:true },
    'ContentType': { type:'Edm.String',nullable:true },
    'Created': { type:'Edm.DateTime',nullable:true },
    'CreatedBy': { type:'Microsoft.SharePoint.DataService.UserInformationListItem',inverseProperty:'$$unbound' },
    'CreatedById': { type:'Edm.Int32',nullable:true },
    'Modified': { type:'Edm.DateTime',nullable:true },
    'ModifiedBy': { type:'Microsoft.SharePoint.DataService.UserInformationListItem',inverseProperty:'$$unbound' },
    'ModifiedById': { type:'Edm.Int32',nullable:true },
    'CopySource': { type:'Edm.String',nullable:true },
    'ApprovalStatus': { type:'Edm.String',nullable:true },
    'Path': { type:'Edm.String',nullable:true },
    'CheckedOutTo': { type:'Microsoft.SharePoint.DataService.UserInformationListItem',inverseProperty:'$$unbound' },
    'CheckedOutToId': { type:'Edm.Int32',nullable:true },
    'Name': { type:'Edm.String',nullable:true },
    'VirusStatus': { type:'Edm.String',nullable:true },
    'IsCurrentVersion': { type:'Edm.Boolean',nullable:true },
    'Owshiddenversion': { type:'Edm.Int32',nullable:true,concurrencyMode:$data.ConcurrencyMode.Fixed },
    'Version': { type:'Edm.String',nullable:true },
    'Description': { type:'Edm.String',nullable:true }
  });
  $data.Entity.extend('Microsoft.SharePoint.DataService.UserInformationListItem', {
    'Id': { key:true,type:'Edm.Int32',nullable:false,required:true },
    'ContentTypeID': { type:'Edm.String',nullable:true },
    'ContentType': { type:'Edm.String',nullable:true },
    'Name': { type:'Edm.String',nullable:true },
    'Modified': { type:'Edm.DateTime',nullable:true },
    'Created': { type:'Edm.DateTime',nullable:true },
    'CreatedBy': { type:'Microsoft.SharePoint.DataService.UserInformationListItem',inverseProperty:'$$unbound' },
    'CreatedById': { type:'Edm.Int32',nullable:true },
    'ModifiedBy': { type:'Microsoft.SharePoint.DataService.UserInformationListItem',inverseProperty:'$$unbound' },
    'ModifiedById': { type:'Edm.Int32',nullable:true },
    'Owshiddenversion': { type:'Edm.Int32',nullable:true,concurrencyMode:$data.ConcurrencyMode.Fixed },
    'Version': { type:'Edm.String',nullable:true },
    'Attachments': { type:'Array',elementType:'Microsoft.SharePoint.DataService.AttachmentsItem',inverseProperty:'$$unbound' },
    'Path': { type:'Edm.String',nullable:true },
    'Account': { type:'Edm.String',nullable:true },
    'EMail': { type:'Edm.String',nullable:true },
    'MobileNumber': { type:'Edm.String',nullable:true },
    'AboutMe': { type:'Edm.String',nullable:true },
    'SIPAddress': { type:'Edm.String',nullable:true },
    'IsSiteAdmin': { type:'Edm.Boolean',nullable:true },
    'Deleted': { type:'Edm.Boolean',nullable:true },
    'Picture': { type:'Edm.String',nullable:true },
    'Department': { type:'Edm.String',nullable:true },
    'JobTitle': { type:'Edm.String',nullable:true }
  });
  $data.Entity.extend('Microsoft.SharePoint.DataService.WebPartGalleryItem', {
    'Id': { key:true,type:'Edm.Int32',nullable:false,required:true },
    'ContentTypeID': { type:'Edm.String',nullable:true },
    'ContentType': { type:'Edm.String',nullable:true },
    'Created': { type:'Edm.DateTime',nullable:true },
    'CreatedBy': { type:'Microsoft.SharePoint.DataService.UserInformationListItem',inverseProperty:'$$unbound' },
    'CreatedById': { type:'Edm.Int32',nullable:true },
    'Modified': { type:'Edm.DateTime',nullable:true },
    'ModifiedBy': { type:'Microsoft.SharePoint.DataService.UserInformationListItem',inverseProperty:'$$unbound' },
    'ModifiedById': { type:'Edm.Int32',nullable:true },
    'CopySource': { type:'Edm.String',nullable:true },
    'ApprovalStatus': { type:'Edm.String',nullable:true },
    'Path': { type:'Edm.String',nullable:true },
    'CheckedOutTo': { type:'Microsoft.SharePoint.DataService.UserInformationListItem',inverseProperty:'$$unbound' },
    'CheckedOutToId': { type:'Edm.Int32',nullable:true },
    'Name': { type:'Edm.String',nullable:true },
    'VirusStatus': { type:'Edm.String',nullable:true },
    'IsCurrentVersion': { type:'Edm.Boolean',nullable:true },
    'Owshiddenversion': { type:'Edm.Int32',nullable:true,concurrencyMode:$data.ConcurrencyMode.Fixed },
    'Version': { type:'Edm.String',nullable:true },
    'Title': { type:'Edm.String',nullable:true },
    'Description': { type:'Edm.String',nullable:true },
    'Group': { type:'Microsoft.SharePoint.DataService.WebPartGalleryGroupValue',inverseProperty:'$$unbound' },
    'GroupValue': { type:'Edm.String',nullable:true },
    'RecommendationSettings': { type:'Array',elementType:'Microsoft.SharePoint.DataService.WebPartGalleryRecommendationSettingsValue',inverseProperty:'$$unbound' }
  });
  $data.Entity.extend('Microsoft.SharePoint.DataService.WebPartGalleryGroupValue', {
    'Value': { key:true,type:'Edm.String',nullable:false,required:true }
  });
  $data.Entity.extend('Microsoft.SharePoint.DataService.WebPartGalleryRecommendationSettingsValue', {
    'Value': { key:true,type:'Edm.String',nullable:false,required:true }
  });
  $data.Entity.extend('Microsoft.SharePoint.DataService.ZurbItem', {
    'Id': { key:true,type:'Edm.Int32',nullable:false,required:true },
    'ContentTypeID': { type:'Edm.String',nullable:true },
    'ContentType': { type:'Edm.String',nullable:true },
    'Created': { type:'Edm.DateTime',nullable:true },
    'CreatedBy': { type:'Microsoft.SharePoint.DataService.UserInformationListItem',inverseProperty:'$$unbound' },
    'CreatedById': { type:'Edm.Int32',nullable:true },
    'Modified': { type:'Edm.DateTime',nullable:true },
    'ModifiedBy': { type:'Microsoft.SharePoint.DataService.UserInformationListItem',inverseProperty:'$$unbound' },
    'ModifiedById': { type:'Edm.Int32',nullable:true },
    'CopySource': { type:'Edm.String',nullable:true },
    'ApprovalStatus': { type:'Edm.String',nullable:true },
    'Path': { type:'Edm.String',nullable:true },
    'CheckedOutTo': { type:'Microsoft.SharePoint.DataService.UserInformationListItem',inverseProperty:'$$unbound' },
    'CheckedOutToId': { type:'Edm.Int32',nullable:true },
    'Name': { type:'Edm.String',nullable:true },
    'VirusStatus': { type:'Edm.String',nullable:true },
    'IsCurrentVersion': { type:'Edm.Boolean',nullable:true },
    'Owshiddenversion': { type:'Edm.Int32',nullable:true,concurrencyMode:$data.ConcurrencyMode.Fixed },
    'Version': { type:'Edm.String',nullable:true },
    'Title': { type:'Edm.String',nullable:true }
  });
  $data.Entity.extend('Microsoft.SharePoint.DataService.ZurbV2Item', {
    'Id': { key:true,type:'Edm.Int32',nullable:false,required:true },
    'ContentTypeID': { type:'Edm.String',nullable:true },
    'ContentType': { type:'Edm.String',nullable:true },
    'Created': { type:'Edm.DateTime',nullable:true },
    'CreatedBy': { type:'Microsoft.SharePoint.DataService.UserInformationListItem',inverseProperty:'$$unbound' },
    'CreatedById': { type:'Edm.Int32',nullable:true },
    'Modified': { type:'Edm.DateTime',nullable:true },
    'ModifiedBy': { type:'Microsoft.SharePoint.DataService.UserInformationListItem',inverseProperty:'$$unbound' },
    'ModifiedById': { type:'Edm.Int32',nullable:true },
    'CopySource': { type:'Edm.String',nullable:true },
    'ApprovalStatus': { type:'Edm.String',nullable:true },
    'Path': { type:'Edm.String',nullable:true },
    'CheckedOutTo': { type:'Microsoft.SharePoint.DataService.UserInformationListItem',inverseProperty:'$$unbound' },
    'CheckedOutToId': { type:'Edm.Int32',nullable:true },
    'Name': { type:'Edm.String',nullable:true },
    'VirusStatus': { type:'Edm.String',nullable:true },
    'IsCurrentVersion': { type:'Edm.Boolean',nullable:true },
    'Owshiddenversion': { type:'Edm.Int32',nullable:true,concurrencyMode:$data.ConcurrencyMode.Fixed },
    'Version': { type:'Edm.String',nullable:true },
    'Title': { type:'Edm.String',nullable:true }
  });
  $data.Entity.extend('Microsoft.SharePoint.DataService.ZurbV3Item', {
    'Id': { key:true,type:'Edm.Int32',nullable:false,required:true },
    'ContentTypeID': { type:'Edm.String',nullable:true },
    'ContentType': { type:'Edm.String',nullable:true },
    'Created': { type:'Edm.DateTime',nullable:true },
    'CreatedBy': { type:'Microsoft.SharePoint.DataService.UserInformationListItem',inverseProperty:'$$unbound' },
    'CreatedById': { type:'Edm.Int32',nullable:true },
    'Modified': { type:'Edm.DateTime',nullable:true },
    'ModifiedBy': { type:'Microsoft.SharePoint.DataService.UserInformationListItem',inverseProperty:'$$unbound' },
    'ModifiedById': { type:'Edm.Int32',nullable:true },
    'CopySource': { type:'Edm.String',nullable:true },
    'ApprovalStatus': { type:'Edm.String',nullable:true },
    'Path': { type:'Edm.String',nullable:true },
    'CheckedOutTo': { type:'Microsoft.SharePoint.DataService.UserInformationListItem',inverseProperty:'$$unbound' },
    'CheckedOutToId': { type:'Edm.Int32',nullable:true },
    'Name': { type:'Edm.String',nullable:true },
    'VirusStatus': { type:'Edm.String',nullable:true },
    'IsCurrentVersion': { type:'Edm.Boolean',nullable:true },
    'Owshiddenversion': { type:'Edm.Int32',nullable:true,concurrencyMode:$data.ConcurrencyMode.Fixed },
    'Version': { type:'Edm.String',nullable:true },
    'Title': { type:'Edm.String',nullable:true }
  });
  $data.EntityContext.extend('app.jaydata.MetroStyleDataContext', {
    Announcements: { type: $data.EntitySet, elementType: Microsoft.SharePoint.DataService.AnnouncementsItem },
      Attachments: { type: $data.EntitySet, elementType: Microsoft.SharePoint.DataService.AttachmentsItem },
      Calendar: { type: $data.EntitySet, elementType: Microsoft.SharePoint.DataService.CalendarItem },
      CalendarCategory: { type: $data.EntitySet, elementType: Microsoft.SharePoint.DataService.CalendarCategoryValue },
      Contacts: { type: $data.EntitySet, elementType: Microsoft.SharePoint.DataService.ContactsItem },
      Custom1: { type: $data.EntitySet, elementType: Microsoft.SharePoint.DataService.Custom1Item },
      DocumentLibrary1: { type: $data.EntitySet, elementType: Microsoft.SharePoint.DataService.DocumentLibrary1Item },
      DocumentLibrary2: { type: $data.EntitySet, elementType: Microsoft.SharePoint.DataService.DocumentLibrary2Item },
      Fpdatasources: { type: $data.EntitySet, elementType: Microsoft.SharePoint.DataService.FpdatasourcesItem },
      FunnyÜÖÄüöäName: { type: $data.EntitySet, elementType: Microsoft.SharePoint.DataService.FunnyÜÖÄüöäNameItem },
      Issues: { type: $data.EntitySet, elementType: Microsoft.SharePoint.DataService.IssuesItem },
      IssuesCategory: { type: $data.EntitySet, elementType: Microsoft.SharePoint.DataService.IssuesCategoryValue },
      IssuesIssueStatus: { type: $data.EntitySet, elementType: Microsoft.SharePoint.DataService.IssuesIssueStatusValue },
      IssuesPriority: { type: $data.EntitySet, elementType: Microsoft.SharePoint.DataService.IssuesPriorityValue },
      Links: { type: $data.EntitySet, elementType: Microsoft.SharePoint.DataService.LinksItem },
      ListTemplateGallery: { type: $data.EntitySet, elementType: Microsoft.SharePoint.DataService.ListTemplateGalleryItem },
      MasterPageGallery: { type: $data.EntitySet, elementType: Microsoft.SharePoint.DataService.MasterPageGalleryItem },
      MasterPageGalleryCompatibleUIVersionS: { type: $data.EntitySet, elementType: Microsoft.SharePoint.DataService.MasterPageGalleryCompatibleUIVersionSValue },
      ProjectTasks: { type: $data.EntitySet, elementType: Microsoft.SharePoint.DataService.ProjectTasksItem },
      ProjectTasksPriority: { type: $data.EntitySet, elementType: Microsoft.SharePoint.DataService.ProjectTasksPriorityValue },
      ProjectTasksTaskStatus: { type: $data.EntitySet, elementType: Microsoft.SharePoint.DataService.ProjectTasksTaskStatusValue },
      ServiceFiles: { type: $data.EntitySet, elementType: Microsoft.SharePoint.DataService.ServiceFilesItem },
      SitePages: { type: $data.EntitySet, elementType: Microsoft.SharePoint.DataService.SitePagesItem },
      SolutionGallery: { type: $data.EntitySet, elementType: Microsoft.SharePoint.DataService.SolutionGalleryItem },
      StyleLibrary: { type: $data.EntitySet, elementType: Microsoft.SharePoint.DataService.StyleLibraryItem },
      Tasks: { type: $data.EntitySet, elementType: Microsoft.SharePoint.DataService.TasksItem },
      TasksPriority: { type: $data.EntitySet, elementType: Microsoft.SharePoint.DataService.TasksPriorityValue },
      TasksStatus: { type: $data.EntitySet, elementType: Microsoft.SharePoint.DataService.TasksStatusValue },
      ThemeGallery: { type: $data.EntitySet, elementType: Microsoft.SharePoint.DataService.ThemeGalleryItem },
      UserInformationList: { type: $data.EntitySet, elementType: Microsoft.SharePoint.DataService.UserInformationListItem },
      WebPartGallery: { type: $data.EntitySet, elementType: Microsoft.SharePoint.DataService.WebPartGalleryItem },
      WebPartGalleryGroup: { type: $data.EntitySet, elementType: Microsoft.SharePoint.DataService.WebPartGalleryGroupValue },
      WebPartGalleryRecommendationSettings: { type: $data.EntitySet, elementType: Microsoft.SharePoint.DataService.WebPartGalleryRecommendationSettingsValue },
      Zurb: { type: $data.EntitySet, elementType: Microsoft.SharePoint.DataService.ZurbItem },
      ZurbV2: { type: $data.EntitySet, elementType: Microsoft.SharePoint.DataService.ZurbV2Item },
      ZurbV3: { type: $data.EntitySet, elementType: Microsoft.SharePoint.DataService.ZurbV3Item },
      ConvertListTitleToEntitySetName: $data.EntityContext.generateServiceOperation({ serviceName:'ConvertListTitleToEntitySetName', returnType: 
        'Edm.String'
      , params: [{ listTitle: 'Edm.String' }], method: 'GET'})
  });
  

  })(window, $data);
      
    